import org.jetbrains.gradle.ext.Gradle

plugins {
    id 'java'
    id 'java-library'
    id 'maven-publish'

    alias(libs.plugins.shadow)
    alias(libs.plugins.ideaExt)
    alias(libs.plugins.unimined)
    alias(libs.plugins.buildConstants)
}

apply from: 'gradle/scripts/helpers.gradle'

// Early Assertions
assertProperty 'mod_version'
assertProperty 'mod_package'
assertProperty 'mod_id'
assertProperty 'mod_name'

assertSubProperties 'use_tags', 'tag_class_name'
assertSubProperties 'use_access_transformer', 'access_transformer_locations'
assertSubProperties 'is_coremod', 'coremod_includes_mod', 'coremod_plugin_class_name'
assertSubProperties 'use_asset_mover', 'asset_mover_version'

setDefaultProperty 'generate_sources_jar', true, false
setDefaultProperty 'generate_javadocs_jar', true, false
setDefaultProperty 'generate_dev_jar', true, false
setDefaultProperty 'minecraft_username', true, 'Developer'
setDefaultProperty 'extra_jvm_args', false, ''

version = propertyString('mod_version')
group = propertyString('mod_package')

base {
    archivesName = propertyString('mod_id')
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(libs.versions.javaToolchain.get())
    }
    if (propertyBool('generate_sources_jar')) {
        withSourcesJar()
    }
    if (propertyBool('generate_javadocs_jar')) {
        withJavadocJar()
    }
}

configurations {
    contain
    implementation.extendsFrom(contain)
    modCompileOnly
    compileOnly.extendsFrom(modCompileOnly)
    modRuntimeOnly
    runtimeOnly.extendsFrom(modRuntimeOnly)
}

String remapTaskName = propertyBool('enable_shadow') ? 'remapShadowJar' : 'remapJar'

unimined.minecraft {
    version propertyString('minecraft_version')

    mappings {
        mcp('stable', '39-1.12')
    }

    cleanroom {
        if (propertyBool('use_access_transformer')) {
            accessTransformer "${rootProject.projectDir}/src/main/resources/${propertyString('access_transformer_locations')}"
        }
        loader propertyString('loader_version')
        runs.auth.username = minecraft_username
        runs.all {
            def extraArgs = propertyString('extra_jvm_args')
            if (extraArgs != null && !extraArgs.trim().isEmpty()) {
                jvmArgs += extraArgs.split { '\\s+' }.toList()
            }
            if (propertyBool('enable_foundation_debug')) {
                systemProperty('foundation.dump', 'true')
                systemProperty('foundation.verbose', 'true')
            }
            if (propertyBool('is_coremod')) {
                systemProperty('fml.coreMods.load', propertyString('coremod_plugin_class_name'))
            }
            return
        }
    }

    defaultRemapJar = false

    String jarTaskName = propertyBool('enable_shadow') ? 'shadowJar' : 'jar'

    remap(tasks.named(jarTaskName).get()) {
    }

    mods {
        remap(configurations.modCompileOnly)
        remap(configurations.modRuntimeOnly)
    }
}

apply from: 'gradle/scripts/repositories.gradle'
apply from: 'gradle/scripts/dependencies.gradle'

processResources {
    var replaceProperties = [
            'mod_id'           : propertyString('mod_id'),
            'mod_name'         : propertyString('mod_name'),
            'mod_version'      : propertyString('mod_version'),
            'mod_description'  : propertyString('mod_description'),
            'mod_credits'      : propertyString('mod_credits'),
            'mod_url'          : propertyString('mod_url'),
            'mod_update_json'  : propertyString('mod_update_json'),
            'mod_logo_path'    : propertyString('mod_logo_path'),
            'mod_authors'      : propertyStringList('mod_authors', ',').collect { it.strip() }.join('\", \"'),
            'minecraft_version': propertyString('minecraft_version'),
    ]

    var filterList = [
            'mcmod.info',
            'pack.mcmeta'
    ]

    inputs.properties replaceProperties
    filesMatching(filterList) { fcd ->
        fcd.expand(replaceProperties)
    }

    if (propertyBool('use_access_transformer')) {
        rename '(.+_at.cfg)', 'META-INF/$1'
    }
}

generateBuildConstants {
    classname = propertyString('tag_class_name')
    includePredefinedConstants = false

    additionalConstants.put('MOD_ID', propertyString('mod_id'))
    additionalConstants.put('MOD_VERSION', propertyString('mod_version'))
    additionalConstants.put('MOD_NAME', propertyString('mod_name'))
    additionalConstants.put('SERVER_PROXY', propertyString('tag_server_proxy'))
    additionalConstants.put('CLIENT_PROXY', propertyString('tag_client_proxy'))
}

if (propertyBool('generate_sources_jar')) {
    tasks.named('sourcesJar', Jar).configure {
        dependsOn tasks.named('generateBuildConstants')
    }
}

idea {
    module {
        inheritOutputDirs = true
        downloadJavadoc = true
        downloadSources = true
    }
    project {
        settings {
            runConfigurations {
                '1. Build'(Gradle) {
                    taskNames = ['build']
                }
                '2. Run Client'(Gradle) {
                    taskNames = ['runClient']
                }
                '3. Run Server'(Gradle) {
                    taskNames = ['runServer']
                }
            }
            compiler.javac {
                afterEvaluate {
                    javacAdditionalOptions = '-encoding utf8'
                    moduleJavacAdditionalOptions = [
                            (project.name + '.main'): tasks.compileJava.options.compilerArgs.collect { '\"' + it + '\"' }.join(' ')
                    ]
                }
            }
        }
    }
}

if (!propertyBool('enable_shadow')) {
    shadowJar.enabled = false
}

shadowJar {
    configurations = [project.configurations.shadow]
    archiveClassifier = 'shadow'
}

compileJava {
    sourceCompatibility = targetCompatibility = JavaVersion.toVersion(libs.versions.javaTarget.get())
}

jar {
    archiveClassifier = propertyBool('generate_dev_jar') ? 'dev' : null
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    if (configurations.contain.size() > 0) {
        into('/') {
            from configurations.contain
        }
    }
    doFirst {
        manifest {
            def attribute_map = [:]
            attribute_map['ModType'] = 'CRL'
            if (configurations.contain.size() > 0) {
                attribute_map['ContainedDeps'] = configurations.contain.collect { it.name }.join(' ')
                attribute_map['NonModDeps'] = true
            }
            if (propertyBool('is_coremod')) {
                attribute_map['FMLCorePlugin'] = propertyString('coremod_plugin_class_name')
                if (propertyBool('coremod_includes_mod')) {
                    attribute_map['FMLCorePluginContainsFMLMod'] = true
                }
            }
            if (propertyBool('use_access_transformer')) {
                attribute_map['FMLAT'] = propertyString('access_transformer_locations')
            }
            attributes(attribute_map)
        }
    }
    finalizedBy(tasks.named(remapTaskName).get())
}

tasks.named(remapTaskName).configure {
    doFirst {
        logging.captureStandardOutput LogLevel.INFO
    }
    doLast {
        logging.captureStandardOutput LogLevel.QUIET
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

apply from: 'gradle/scripts/testing.gradle'
apply from: 'gradle/scripts/publishing.gradle'
apply from: 'gradle/scripts/extra.gradle'
